### ISSUE TITLE
keypad back button doesn't remove 

### ISSUE THREAD

**Issue by MohamedHamada12** [Onum/EditCodeView#1]
this lib is very good effort and work fine but I can't remove. back button on keypad don't make anything
and this method doesn't work  
 editCodeView.clearCode();

**Comment by iurysza** [comment]
Same problem here

**Comment by MohamedHamada12** [comment]
Please will you make any update to close this issue ?

**Comment by Onum** [comment]
@MohamedHamada12 @iurysza Hi. You could now test a new version 1.0.4 with this fix. Thank you for pointing out this issue.
